### ISSUE TITLE
Issue running mnist example

### ISSUE THREAD

**Issue by y0sif** [VlaDexa/burn-efficient-kan#2]
when I tried running the mnist example you have in your code I got this error:

error: process didn't exit successfully: `target\release\examples\mnist.exe` (exit code: 0xc06d007e)

how can I solve this error?

**Comment by Khaled-Ayman1** [comment]
Same issue here, tried switching my complier to gnu jnstead of msvc, same error

**Comment by VlaDexa** [comment]
Oh, you're running on Windows? You should then switch ndarray-linalg features to Intel stuff from netlib and ensure that you have that installed. Sadly, that crate works on Windows only with Intel MLK.

**Comment by y0sif** [comment]
i downloaded intel mlk and ran the ndarray-linalg with it, it ran but gave me more errors, so I switched to linux using wsl, and I was able to run the code with no issues.
